name: app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  animated_splash_screen: ^1.1.0
  mysql1: ^0.20.0
  mysql_utils: ^1.0.2
  hive: null
  hive_flutter: null
  sqflite: any
  path_provider: any
  flutter_slidable: any
  image_picker: ^0.8.6
  flutter_barcode_scanner: ^2.0.0
  provider: ^4.0.4
  intl: ^0.17.0
  dropdown_button2: ^1.8.9
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^4.1.1
  internet_connection_checker: ^1.0.0+1
  multi_trigger_autocomplete: ^0.1.1
  socket_io_client: ^2.0.0
  dart_ping: ^7.0.2
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib\assets\images\sary.jpg
    - lib\assets\images\logoinfo.png
    - lib\assets\images\varika1.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
